config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

	get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'

	get		'/info/' => 'info#index', as: :info

	resources :users do
	  resources :favorites
	end
	resources :cars do
		resources :comments

	end

  get  '/users/:id/cars' => 'users#cars', as: :user_cars
  get  '/users/:id/favs' =>'users#favs', as: :user_favs

	get '/admin/cars' => 'admin#cars', as: :admin_cars
	get '/admin/users' => 'admin#users', as: :admin_users
  post '/cars/s/search' => 'cars#search', as: :cars_search

  get '/api/users' =>'api#users'
  get '/api/cars'  =>'api#cars'
  get '/api/carsfavs' => 'api#carsfavs'
  post '/api/cars' => 'api#create'
  get '/api/favs'  =>'api#favs'
  get '/api/favdestroy' => 'api#favsdestroy'
  post '/api/favs' => 'api#createfavs'
  get '/api/comments' =>'api#comments'
  post '/api/comments' => 'api#createcomments'
	get '/api/login' => 'api#login'
  post '/api/signup' => 'api#signup'
  get '/api/sort' => 'api#sort'

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
	before_save {
		self.email = email.downcase
		self.username = username.downcase
	}
	before_destroy {
		cars = self.cars.delete_all
	}
  validates :username, presence: true, length: { maximum: 20 },
	uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
	format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, if: :password
  has_many :cars, :dependent => :destroy
	has_many :favorites, :dependent => :destroy

	def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
	def User.new_token
		SecureRandom.urlsafe_base64
	end
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end
	def authenticated?(remember_token)
		return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
		if did_login?
			redirect_to user_cars_path(current_user)
		else
			@user = User.new()
		end
  end
  def create
    @user = User.new(params.require(:user).permit(:username, :email, :password, :password_confirmation))
		@user.isadmin = false
		respond_to do |format|
			if @user.save
				session[:user_id] = @user.id
				format.js {  }
			else
				format.js {  }
			end
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to  admin_users_path
  end
	def favs
		@favs = current_user.favorites.order(created_at: :desc)
		@cars = @favs.collect {|fav| fav.car}
	end
	def cars
		@cars = current_user.cars.order(created_at: :desc)
	end
  def update
    @user = User.find(params[:id])
    if params[:isadmin] == "true"
      @user.update(isadmin: false)
    end
    if params[:isadmin] == "false"
      @user.update(isadmin: true)
    end
    redirect_to admin_users_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_item.html.erb
<% @users = pagination(@users) %>
<md-card layout="row">
<div flex layout-padding>
<% @users.each do |user| %>
			<md-list flex>
        <md-list-item class="md-2-line" ng-cloak>
					<div class="md-list-item-text" layout="column">
						<div><md-icon md-font-set="material-icons">person</md-icon> <%= user.username%>
						</div>
						<div><md-icon md-font-set="material-icons">mail_outline</md-icon> <%= user.email%></div>
          </div>
					<% if user.isadmin==true %>
						<span class="admin">admin</span>
					<% end %>
					<div flex></div>
<md-fab-speed-dial md-direction="left" class="md-fling">
  <md-fab-trigger>
    <md-button class="md-fab md-primary md-button md-ink-ripple"><md-icon md-font-set="material-icons">mode_edit</md-icon></md-button>
  </md-fab-trigger>
  <md-fab-actions>
		<% if current_user.username != user.username %>
    <md-button ng-href="<%=user_path(user.id)%>" data-method="delete" class="md-fab md-mini md-ink-ripple">
			<md-icon md-font-set="material-icons">delete</md-icon>
			<md-tooltip md-direction="top">Delete</md-tooltip>
		</md-button>
    <% end %>

		<md-button ng-href="<%=user_path(user.id,:isadmin => user.isadmin)%>" data-method="patch" class="md-fab md-mini md-ink-ripple">
      <% if user.isadmin==true%>
			<md-icon md-font-set="material-icons">file_download</md-icon>
			<md-tooltip md-direction="top">Unset Admin</md-tooltip>
      <% else %>
			<md-icon md-font-set="material-icons">file_upload</md-icon>
			<md-tooltip md-direction="top">Set Admin</md-tooltip>
     <% end %>
 	</md-button>





  </md-fab-actions>
</md-fab-speed-dial>
        </md-list-item>
      </md-list>
<md-divider ></md-divider>
<%end%>
	<%= will_paginate @users %>
</md-card>
</div>

app/views/users/_side.html.erb
<div layout="row" layout-xs="column">
	<div flex="10" hide-xs hide-sm></div>
	<div flex-gt-sm="20" flex-sm="30">
	<md-card layout="column" layout-xs="row" layout-padding layout-align="space-around stretch">
<md-button class="md-raised" ng-href="<%=user_cars_path(current_user)%>">MY CARS</md-button>
<md-button class="md-raised" ng-href="<%=user_favs_path(current_user)%>">MY FAVS</md-button>
<% if current_user.isadmin == true%>
<md-button class="md-raised" ng-href="<%=admin_cars_path%>">MANAGE CARS</md-button>
<md-button class="md-raised" ng-href="<%=admin_users_path%>">MANAGE USERS</md-button>
<%end%>
</md-card>
</div>
	<div flex>

app/views/users/cars.html.erb
	<%= render 'users/side'%>
	<%= render 'cars/item' %>

	</div>

	<div flex="10" hide-xs hide-sm></div>
</div>

app/views/users/create.js.erb
$('.md-errors-spacer:eq(0)').text("");
$('.md-errors-spacer:eq(1)').text("");
$('.md-errors-spacer:eq(2)').text("");
$('.md-errors-spacer:eq(3)').text("");
<% if @user.errors[:username].count != 0 %>
$('.md-errors-spacer:eq(0)').text("username <%= @user.errors[:username].first%>");
<% elsif @user.errors[:email].count != 0 %>
$('.md-errors-spacer:eq(1)').text("email <%= @user.errors[:email].first%>");
<% elsif @user.errors[:password].count != 0 %>
$('.md-errors-spacer:eq(2)').text("password <%= @user.errors[:password].first%>");
<% elsif @user.errors[:password_confirmation].count != 0 %>
$('.md-errors-spacer:eq(3)').text("password <%= @user.errors[:password_confirmation].first%>");
<% else %>
window.location.href = '/'
<% end %>

app/views/users/favs.html.erb
	<%= render 'users/side'%>
	<%= render 'cars/item' %>

	</div>

	<div flex="10" hide-xs hide-sm></div>
</div>

app/views/users/index.html.erb
<%= render 'users/side' %>
<% @users.each do |user| %>
username:<%=user.username%>
emial:<%= user.email%>
isadmin:<%= user.isadmin%>
<%= form_for :user, url:user_path(user.id),method: :patch do |f|%>
<%= f.select :isadmin,[['No',0],['Yes',1]]%>
<%= f.submit %>
<%end%>
<%= link_to 'Delete', user_path(user.id),method: :delete, data:{confirm: ' Are you sure'}%><br>
<%end%>

app/views/users/login_form.html.erb
<% if @login_fail == 1 %> 
	Username Incorrect.
<% end %>
<% if @login_fail == 2 %> 
	Password Doesn't Match.
<% end %>

<%= form_for :user, url: user_login_path, class: 'text' do |f|%>
	<%= f.text_field :username, placeholder:'Username', class: 'underline_textfield' %><br>

	<%= f.text_field :password, placeholder:'Password', class: 'underline_textfield', type: "password" %><br>

	<%= f.submit 'LOGIN', class: 'btn btn-default'%>
<% end %>

app/views/users/managercar.html.erb
<% @cars.each do |car|%>
<div class="car ">
 <div class="col-sm-3 ">
   <div class=""><%= image_tag("/assets/user_car/#{car.picture}", :alt => "rss feed") %></div>
 </div>
 <%= link_to car_path(car.id) do %>
 <div class="col-sm-9 ">
   <div class="cartitle"><%=car.year%><%=car.make%><%=car.model%></div>
   <div class="carprice">$<%=car.price%></div>
   <div class="carmileage"><%=car.mileage%>mi</div>
   <div class="carlocation"><%=car.state%><%=car.city%></div>
   <div class="carseller">post by:<%=car.user.username%></div>
   <div class="carcontact">contact:<%=car.contact%></div>
   <%= link_to 'Delete',car_path(car.id), method: :DELETE,data:{confirm: 'Are you sure?'}%>
 </div>
 <%end %>
</div>
<% end %>

app/views/users/mycars.html.erb
<h3>the car this user sell</h3>
<% current_user.cars.each do |car| %>
 <div class="carlist ">
  <div class="col-sm-3 ">
    <div class=""><%= image_tag("/assets/user_car/#{car.picture}", :alt => "rss feed") %></div>
  </div>
  <%= link_to car_path(car.id) do %>
  <div class="col-sm-9 ">
    <div class="cartitle"><%=car.year%><%=car.make%><%=car.model%></div>
    <div class="carprice">$<%=car.price%></div>
    <div class="carmileage"><%=car.mileage%>mi</div>
    <div class="carlocation"><%=car.state%><%=car.city%></div>
    <div class="carseller">post by:<%=car.user.username%></div>
    <div class="carcontact">contact:<%=car.contact%></div>
  </div>
  <%end %>
</div>
<% end %>

app/views/users/myfav.html.erb
<h3>the car this user favorite</h3>
<% current_user.favorites.each do |favorite| %>
 <div class="car">
 <div class="col-sm-3 ">
   <div class=""><%= image_tag("/assets/user_car/#{favorite.car.picture}", :alt => "rss feed") %></div>
 </div>
 <%= link_to car_path(favorite.car.id) do %>
 <div class="col-sm-9 ">
   <div class="carseller">post by:<%=favorite.user.username%></div>
   <div class="carcontact">contact:<%=favorite.car.contact%></div>
 </div>
 <%end %>
 </div>
<%end%>

app/views/users/new.html.erb
<div layout="row">
<div flex></div>
<div>
<md-card>
<md-content class="login">

<%= form_for :user, url: users_path, remote: true do |f|%>
<md-input-container>
	<label>Username</label>
	<%= f.text_field :username %><br>
</md-input-container>

<br>

<md-input-container>
	<label>Email</label>
	<%= f.text_field :email %><br>
</md-input-container>

<br>

<md-input-container>
	<label>Password</label>
	<%= f.text_field :password, :type => 'password' %><br>
</md-input-container>

<br>

<md-input-container>
	<label>Confirm Password</label>
	<%= f.text_field :password_confirmation, :type => 'password' %><br>
</md-input-container>

<br>

	<md-button class="md-raised" type="submit">SIGNUP</md-button></br>
<% end %>

</md-content>
</md-card>
</div>
<div flex></div>
</div>

app/views/users/signup_form.html.erb
<% if @user.errors.any? %>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
<% end %>

<%= form_for :user, url: user_signup_path do |f|%>
	<%= f.text_field :username, placeholder:'Username', class: 'underline_textfield' %><br>

	<%= f.text_field :email, placeholder:'Email', class: 'underline_textfield' %><br>

	<%= f.text_field :password, placeholder:'Password', class: 'underline_textfield' %><br>

	<%= f.text_field :password_confirmation, placeholder:'Password Confirmation', class: 'underline_textfield' %><br>

	<%= f.submit 'SIGNUP', class: 'btn btn-default' %>
<% end %>