config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

	get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'

	get		'/info/' => 'info#index', as: :info

	resources :users do
	  resources :favorites
	end
	resources :cars do
		resources :comments

	end

  get  '/users/:id/cars' => 'users#cars', as: :user_cars
  get  '/users/:id/favs' =>'users#favs', as: :user_favs

	get '/admin/cars' => 'admin#cars', as: :admin_cars
	get '/admin/users' => 'admin#users', as: :admin_users
  post '/cars/s/search' => 'cars#search', as: :cars_search

  get '/api/users' =>'api#users'
  get '/api/cars'  =>'api#cars'
  get '/api/carsfavs' => 'api#carsfavs'
  post '/api/cars' => 'api#create'
  get '/api/favs'  =>'api#favs'
  get '/api/favdestroy' => 'api#favsdestroy'
  post '/api/favs' => 'api#createfavs'
  get '/api/comments' =>'api#comments'
  post '/api/comments' => 'api#createcomments'
	get '/api/login' => 'api#login'
  post '/api/signup' => 'api#signup'
  get '/api/sort' => 'api#sort'

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :user
  validates :year,:make,:model,:mileage,:price,:contact,:city,:state, presence: true
  validates :price, numericality: {only_integer: true}
  validates :city, format: {with: /\A[a-zA-Z]+\z/, message:"only allows letters"}
  validates  :state, format: {with:/\A[a-zA-Z]+\z/, message:"only allows letters"}
  has_many :comments,  :dependent => :delete_all
  has_many :favorites, :dependent => :delete_all
end


app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
		@sort = params[:sort]
		case @sort
			when '0'
				@cars = Car.where(issold: false).order(created_at: :desc)
			when '1'
				@cars = Car.where(issold: false).order(price: :desc)
			when '2'
				@cars = Car.where(issold: false).order(:price)
			when '3'
				@cars = Car.where(issold: false).order(mileage: :desc)
			when '4'
				@cars = Car.where(issold: false).order(:mileage)
			when '5'
				@cars = Car.where(issold: false).order(year: :desc)
			when '6'
				@cars = Car.where(issold: false).order(:year)
			when '7'
				@cars = Car.where(issold: false).order(:make, :model)
			else
				@cars = Car.where(issold: false).order(created_at: :desc)
		end
	end

	def new
		if did_login?
			@car = Car.new
		else
			redirect_to login_path
		end
	end

	def create
		@car = Car.new(params.require(:car).permit(:year, :make, :model, :mileage, :price, :contact, :city, :state,:notes))
		respond_to do |format|
		@car.user_id = current_user.id
		@car.issold = false
		if @car.save
			#save picture name = userid-carid
			uploaded_io = params[:car][:picture]
      if uploaded_io
  			@car.picture = @car.user_id.to_s+"-"+@car.id.to_s+File.extname(uploaded_io.original_filename)
  			@car.save
  			#upload picture
  			File.open(Rails.root.join('app','assets','images','user_car',@car.picture.to_s),'wb') do |file|
  				file.write(uploaded_io.read)
        end
      else
        @car.picture = 'default.jpg'
        @car.save
      end
			format.js {  }
	  else
			format.js {  }
		end
		end
	end

  def show
		@car = Car.find(params[:id])
	end

  def destroy
  	@car = Car.find(params[:id])
    @car.destroy
    redirect_to  admin_cars_path
  end

  def update
    @car = Car.find(params[:id])
    if params[:issold] == "true"
      @car.update(issold: false)
    end
    if params[:issold] == "false"
      @car.update(issold: true)
    end
    redirect_to car_path(@car)
  end
  def search
		@cars = Car.all
		if params[:car][:make] != ""
			@cars = @cars.select{|a| a.make.downcase == params[:car][:make].downcase}
		end
		if params[:car][:model] != ""
			@cars = @cars.select{|a| a.model.downcase == params[:car][:model].downcase}
		end
		if params[:car][:year] != ""
			@cars = @cars.select{|a| a.year.to_s == params[:car][:year]}
		end
		render 'cars/index'
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_item.html.erb
<% @cars = pagination(@cars) %>

<div layout="row">
<div flex>
  <% @cars.each do |car| %>
<md-card>
        <md-card-title>
          <md-card-title-text>
            <div class="md-headline"><%=car.year%> <%=car.make%> <%=car.model%></div>
						<div><span class="md-display-1">$<%=car.price%> </span>	<span class="md-headline"> <%=car.mileage%> mi</span> </div>
						<div>
						<md-button class='md-icon-button'><md-icon md-font-set="material-icons">location_on</md-icon></md-button>
						 <%=car.city%>, <%=car.state%></div>
						<div>
						<md-button class='md-icon-button'><md-icon md-font-set="material-icons">person</md-icon></md-button>
						<%=car.user.username.capitalize%></div>
						<div>
						<md-button class='md-icon-button'><md-icon md-font-set="material-icons">phone</md-icon></md-button>
						<%=car.contact%></div>
						<div>
          <% if did_login? && Favorite.where(car_id: car.id, user_id: current_user.id).count == 0 %>
          <md-button class='md-icon-button' ng-href="<%= user_favorites_path(current_user.id, :car_id => car.id)%>" data-method="post"><md-icon style="color: rgb(255, 82, 82);" md-font-set="material-icons">favorite_border</md-icon></md-button>
          <% end %>
          <% if did_login? &&  Favorite.where(car_id: car.id, user_id: current_user.id).count != 0 %>
          <% @fav = Favorite.where(car_id: car.id, user_id: current_user.id).ids%>
          <md-button class='md-icon-button' ng-href="<%= user_favorite_path(current_user.id, @fav.first)%>" data-method="delete"><md-icon style="color: rgb(255, 82, 82);" md-font-set="material-icons">favorite</md-icon></md-button>
          <% end %>
					<% if did_login? %>
          <md-button class='md-icon-button' ng-href="<%= car_path(car.id)%>"><md-icon md-font-set="material-icons">description</md-icon></md-button>
					<% end %>
          <% if did_login? &&  current_user.isadmin == true%>
          <md-button class='md-icon-button' ng-href="<%= car_path(car.id)%>" data-method="delete"><md-icon md-font-set="material-icons">delete</md-icon></md-button>
    			<% end %>
					</div>
 
          </md-card-title-text>
          <md-card-title-media>
            <div class="md-media-lg card-media" style="background-image: url('/assets/user_car/<%=car.picture.to_s%>');"></div>
          </md-card-title-media>
        </md-card-title>
      </md-card>
  <% end %>
  <%= will_paginate @cars %>
</div>
</div>

app/views/cars/_makeSelect.html.erb
        <label>Make</label>
        <md-select ng-model="make" ng-change="makeSelected()">
				  <md-option value="Acura">Acura</md-option>
					<md-option value="Alfa Romeo">Alfa Romeo</md-option>
				  <md-option value="Am General">Am General</md-option>
					<md-option value="Aston Martin">Aston Martin</md-option>
				  <md-option value="Audi">Audi</md-option>
					<md-option value="Avanti Motors">Avanti Motors</md-option>
				  <md-option value="Bentley">Bentley</md-option>
					<md-option value="BMW">BMW</md-option>
				  <md-option value="Bugatti">Bugatti</md-option>
					<md-option value="Buick">Buick</md-option>
				  <md-option value="Cadillac">Cadillac</md-option>
					<md-option value="Chevrolet">Chevrolet</md-option>
				  <md-option value="Chrysler">Chrysler</md-option>
					<md-option value="Daewoo">Daewoo</md-option>
				  <md-option value="Dodge">Dodge</md-option>
					<md-option value="Ferrari">Ferrari</md-option>
				  <md-option value="FIAT">FIAT</md-option>
					<md-option value="Fisker">Fisker</md-option>
				  <md-option value="Ford">Ford</md-option>
					<md-option value="GMC">GMC</md-option>
				  <md-option value="Honda">Honda</md-option>
					<md-option value="Hummer">Hummer</md-option>
				  <md-option value="Hyundai">Hyundai</md-option>
					<md-option value="Infiniti">Infiniti</md-option>
				  <md-option value="International">International</md-option>
					<md-option value="Isuzu">Isuzu</md-option>
				  <md-option value="Jaguar">Jaguar</md-option>
					<md-option value="Jeep">Jeep</md-option>
				  <md-option value="Kia">Kia</md-option>
					<md-option value="Koenigsegg">Koenigsegg</md-option>
					<md-option value="Lamborghini">Lamborghini</md-option>
					<md-option value="Land Rover">Land Rover</md-option>
					<md-option value="Lexus">Lexus</md-option>
					<md-option value="Lincoln">Lincoln</md-option>
					<md-option value="Lotus">Lotus</md-option>
					<md-option value="Maserati">Maserati</md-option>
					<md-option value="Maybach">Maybach</md-option>
					<md-option value="Mazda">Mazda</md-option>
					<md-option value="McLaren">McLaren</md-option>
					<md-option value="Mercedes-Benz">Mercedes-Benz</md-option>
					<md-option value="Mercury">Mercury</md-option>
					<md-option value="MINI">MINI</md-option>
					<md-option value="Mitsubishi">Mitsubishi</md-option>
					<md-option value="Morgan">Morgan</md-option>
					<md-option value="Nissan">Nissan</md-option>
					<md-option value="Oldsmobile">Oldsmobile</md-option>
					<md-option value="Panoz">Panoz</md-option>
					<md-option value="Plymouth">Plymouth</md-option>
					<md-option value="Pontiac">Pontiac</md-option>
					<md-option value="Porsche">Porsche</md-option>
					<md-option value="Qvale">Qvale</md-option>
					<md-option value="RAM">RAM</md-option>
					<md-option value="Rolls-Royce">Rolls-Royce</md-option>
					<md-option value="Saab">Saab</md-option>
					<md-option value="Saleen">Saleen</md-option>
					<md-option value="Saturn">Saturn</md-option>
					<md-option value="Scion">Scion</md-option>
					<md-option value="smart">smart</md-option>
					<md-option value="Spyker">Spyker</md-option>
					<md-option value="Subaru">Subaru</md-option>
					<md-option value="Suzuki">Suzuki</md-option>
					<md-option value="Tesla">Tesla</md-option>
					<md-option value="Toyota">Toyota</md-option>
					<md-option value="Volkswagen">Volkswagen</md-option>
					<md-option value="Volvo">Volvo</md-option>
        </md-select>
				<div class="md-errors-spacer"></div>

app/views/cars/_stateSelect.html.erb
        <label>State</label>
        <md-select ng-model="state" ng-change="stateSelected()">
          <md-option value="AL">AL</md-option>
					<md-option value="AK">AK</md-option>
					<md-option value="AZ">AZ</md-option>
					<md-option value="AR">AR</md-option>
					<md-option value="CA">CA</md-option>
					<md-option value="CO">CO</md-option>
					<md-option value="CT">CT</md-option>
					<md-option value="DE">DE</md-option>
					<md-option value="FL">FL</md-option>
					<md-option value="GA">GA</md-option>
					<md-option value="HI">HI</md-option>
					<md-option value="ID">ID</md-option>
					<md-option value="IL">IL</md-option>
					<md-option value="IN">IN</md-option>
					<md-option value="IA">IA</md-option>
          <md-option value="KS">KS</md-option>
					<md-option value="KY">KY</md-option>
					<md-option value="LA">LA</md-option>
					<md-option value="ME">ME</md-option>
					<md-option value="MD">MD</md-option>
					<md-option value="MA">MA</md-option>
					<md-option value="MI">MI</md-option>
					<md-option value="MN">MN</md-option>
					<md-option value="MS">MS</md-option>
					<md-option value="MO">MO</md-option>
					<md-option value="MT">MT</md-option>
					<md-option value="NE">NE</md-option>
					<md-option value="NV">NV</md-option>
					<md-option value="NH">NH</md-option>
					<md-option value="NJ">NJ</md-option>
					<md-option value="NM">NM</md-option>
					<md-option value="NY">NY</md-option>
					<md-option value="NC">NC</md-option>
					<md-option value="ND">ND</md-option>
					<md-option value="OH">OH</md-option>
					<md-option value="OK">OK</md-option>
					<md-option value="OR">OR</md-option>
					<md-option value="PA">PA</md-option>
					<md-option value="RI">RI</md-option>
					<md-option value="SC">SC</md-option>
					<md-option value="SD">SD</md-option>
					<md-option value="TN">TN</md-option>
					<md-option value="TX">TX</md-option>
					<md-option value="UI">UT</md-option>
					<md-option value="VI">VT</md-option>
					<md-option value="VA">VA</md-option>
					<md-option value="WA">WA</md-option>
					<md-option value="WV">WV</md-option>
					<md-option value="WI">WI</md-option>
					<md-option value="WY">WY</md-option>	
        </md-select>
				<div class="md-errors-spacer"></div>

app/views/cars/_yearSelect.html.erb
        <label>Year</label>
        <md-select ng-model="year" ng-change="yearSelected()">
          <md-option value="2016">2016</md-option>
					<md-option value="2015">2015</md-option>
					<md-option value="2014">2014</md-option>
					<md-option value="2013">2013</md-option>
					<md-option value="2012">2012</md-option>
					<md-option value="2011">2011</md-option>
					<md-option value="2010">2010</md-option>
					<md-option value="2009">2009</md-option>
					<md-option value="2008">2008</md-option>
					<md-option value="2007">2007</md-option>
					<md-option value="2006">2006</md-option>
					<md-option value="2005">2005</md-option>
					<md-option value="2004">2004</md-option>
					<md-option value="2003">2003</md-option>
					<md-option value="2002">2002</md-option>
					<md-option value="2001">2001</md-option>
					<md-option value="2000">2000</md-option>
					<md-option value="1999">1999</md-option>
					<md-option value="1998">1998</md-option>
					<md-option value="1997">1997</md-option>
					<md-option value="1996">1996</md-option>
					<md-option value="1995">1995</md-option>
					<md-option value="1994">1994</md-option>
					<md-option value="1993">1993</md-option>
        </md-select>
				<div class="md-errors-spacer"></div>

app/views/cars/create.js.erb
$('.md-errors-spacer:eq(0)').text("");
$('.md-errors-spacer:eq(1)').text("");
$('.md-errors-spacer:eq(2)').text("");
$('.md-errors-spacer:eq(3)').text("");
$('.md-errors-spacer:eq(4)').text("");
$('.md-errors-spacer:eq(5)').text("");
$('.md-errors-spacer:eq(6)').text("");
$('.md-errors-spacer:eq(7)').text("");
$('.md-errors-spacer:eq(8)').text("");
<% if @car.errors[:year].count != 0 %>
$('.md-errors-spacer:eq(0)').text("year <%= @car.errors[:year].first%>");
<% elsif @car.errors[:make].count != 0 %>
$('.md-errors-spacer:eq(1)').text("make <%= @car.errors[:make].first%>");
<% elsif @car.errors[:model].count != 0 %>
$('.md-errors-spacer:eq(2)').text("model <%= @car.errors[:model].first%>");
<% elsif @car.errors[:mileage].count != 0 %>
$('.md-errors-spacer:eq(3)').text("mileage <%= @car.errors[:mileage].first%>");
<% elsif @car.errors[:price].count != 0 %>
$('.md-errors-spacer:eq(4)').text("price <%= @car.errors[:price].first%>");
<% elsif @car.errors[:state].count != 0 %>
$('.md-errors-spacer:eq(5)').text("state <%= @car.errors[:state].first%>");
<% elsif @car.errors[:city].count != 0 %>
$('.md-errors-spacer:eq(6)').text("city <%= @car.errors[:city].first%>");
<% elsif @car.errors[:contact].count != 0 %>
$('.md-errors-spacer:eq(7)').text("contact <%= @car.errors[:contct].first%>");
<% else %>
window.location.href = '<%= user_cars_path(current_user)%>'
<% end %>

app/views/cars/index.html.erb
<div layout="row" layout-xs="column">
	<div flex="10" hide-xs hide-sm></div>
  <div flex-gt-sm="20" flex-sm="30" class="side">
		<md-card layout-padding>

			<%= form_for :car, url: cars_search_path do |f| %>

				<%= f.text_field :year, :style => 'display: none' %>
				<%= f.text_field :make, :style => 'display: none' %>

			<div layout="column" layout-xs="row" layout-align-xs="space-around center">
			<md-input-container flex>
				<%= render 'cars/yearSelect'%>
			</md-input-container>

			<md-input-container flex>
				<%= render 'cars/makeSelect'%>
      </md-input-container>

			<md-input-container flex>
				<label>Mode</label>
				<%= f.text_field :model %><br>
			</md-input-container>

			<md-button class="md-raised" type="submit">SUBMIT</md-button>
			</div>
	<%end%>

		</md-card>

		<md-card layout-padding>
			<div layout="column" layout-xs="row" layout-wrap>
			<md-button class="md-raised" ng-href="<%= cars_path + "?" + {sort: 0}.to_param %>">
			Post Date
			<md-icon md-font-set="material-icons">trending_down</md-icon>
			</md-button>
			<md-button class="md-raised" ng-href="<%= cars_path + "?" + {sort: 7}.to_param %>">
			Make/Mode
			<md-icon md-font-set="material-icons">trending_up</md-icon>
			</md-button>
			<md-button class="md-raised" ng-href="<%= cars_path + "?" + {sort: 1}.to_param %>">
			Price
			<md-icon md-font-set="material-icons">trending_down</md-icon>
			</md-button>
			<md-button class="md-raised" ng-href="<%= cars_path + "?" + {sort: 2}.to_param %>">
			Price
			<md-icon md-font-set="material-icons">trending_up</md-icon>
			</md-button>
			<md-button class="md-raised" ng-href="<%= cars_path + "?" + {sort: 3}.to_param %>">
			Mileage
			<md-icon md-font-set="material-icons">trending_down</md-icon>
			</md-button>
			<md-button class="md-raised" ng-href="<%= cars_path + "?" + {sort: 4}.to_param %>">
			Mileage
			<md-icon md-font-set="material-icons">trending_up</md-icon>
			</md-button>
			<md-button class="md-raised" ng-href="<%= cars_path + "?" + {sort: 5}.to_param %>">
			Year
			<md-icon md-font-set="material-icons">trending_down</md-icon>
			</md-button>
			<md-button class="md-raised" ng-href="<%= cars_path + "?" + {sort: 6}.to_param %>">
			Year
			<md-icon md-font-set="material-icons">trending_up</md-icon>
			</md-button>
			</div>

		</md-card>

  </div>

  <div flex>

<%= render 'cars/item' %>
  </div>

  <div flex="10" hide-xs hide-sm></div>
</div>

app/views/cars/list.html.erb
<div class="container-fluid">
  <div class="row content">
  <% @cars.each do |car| %>
   <div class="carlist ">
    <div class="col-sm-3 ">
      <div class=""><%= image_tag("/assets/user_car/#{car.picture}", :alt => "rss feed") %></div>
    </div>
    <%= link_to car_show_path(car.id) do %>
    <div class="col-sm-9 ">
      <div class="cartitle"><%=car.year%><%=car.make%><%=car.model%></div>
      <div class="carprice">$<%=car.price%></div>
      <div class="carmileage"><%=car.mileage%>mi</div>
      <div class="carlocation"><%=car.state%><%=car.city%></div>
      <div class="carseller">post by:<%=car.user.username%></div>
      <div class="carcontact">contact:<%=car.contact%></div>
    </div>
    <%end %>
  </div>
  <% end %>
</div>
</div>

app/views/cars/new.html.erb
<div layout="row">

<%= @car.errors.first %> 
<div flex="10" hide-xs></div>

<div layout="column" flex>
	<md-card>
		<md-card-content>
			<%= form_for :car , url: cars_path, remote: true do |f| %>

			<div layout="row">

			<%= f.text_field :year, :style => 'display: none'%><br>
			<%= f.text_field :make, :style => 'display: none'%><br>
			<%= f.text_field :state, :style => 'display: none'%><br>

			<md-input-container flex>
			<%= render 'cars/yearSelect' %>
      </md-input-container>

			<md-input-container flex>
			<%= render 'cars/makeSelect' %>
      </md-input-container>

			<md-input-container flex="50">
				<label>Model</label>
				<%= f.text_field :model %><br>
			</md-input-container>

			</div>

			<div layout="row">
			<md-input-container flex="50">
				<label>Mileage</label>
				<%= f.text_field :mileage %><br>
			</md-input-container>
			<md-input-container flex="50">
				<label>Price</label>
				<%= f.text_field :price %><br>
			</md-input-container>

			</div>

			<div layout="row">
			<md-input-container flex="50">
				<%= render 'cars/stateSelect' %>
      </md-input-container>

			<md-input-container flex="50">
				<label>City</label>
				<%= f.text_field :city %><br>
			</md-input-container>

			</div>

			<div layout="column">
			<md-input-container>
				<label>Contact</label>
				<%= f.text_field :contact %><br>
			</md-input-container>
			</div>


			<%= f.text_area(:notes, cols: 30,rows: 1, :style=> 'display:none' )%>
			<md-input-container class="md-block">
          <label>Notes</label>
          <textarea ng-change="notesChange()" ng-model="notes" md-maxlength="256" rows="5" md-select-on-focus></textarea>
			</md-input-container>

			<div layout="row">
			<%= f.file_field :picture, :style=> 'display:none' %>
			<label for="car_picture" class="md-button md-raised">Choose File</label>
			<div id="filename"></div>

			<div flex></div>

			<md-button class="md-raised" type="submit">SUBMIT</md-button>

			</div>

			<% end %>
		</md-card-content>
	</md-card>
</div>

<div flex="10" hide-xs></div>

</div>

app/views/cars/show.html.erb
<div layout="row">

<div flex="10" hide-xs hide-sm></div>

<div flex layout="column">
<md-card layout="row" layout-xs="column">
	<div class="car_show_img" style="background-image: url('/assets/user_car/<%=@car.picture.to_s%>');">
	</div>

	<div flex layout-padding>
            <div class="md-headline"><%=@car.year%> <%=@car.make%> <%=@car.model%></div>
						<div><span class="md-display-1">$<%=@car.price%> </span>	<span class="md-headline"> <%=@car.mileage%> mi</span> </div>
						<div>
						<md-button class='md-icon-button'><md-icon md-font-set="material-icons">location_on</md-icon></md-button>
						 <%=@car.city%>, <%=@car.state%></div>
						<div>
						<md-button class='md-icon-button'><md-icon md-font-set="material-icons">person</md-icon></md-button>
						<%=@car.user.username.capitalize%></div>
						<div>
						<md-button class='md-icon-button'><md-icon md-font-set="material-icons">phone</md-icon></md-button>
						<%=@car.contact%></div>

						<div>
						<md-button class='md-icon-button'><md-icon md-font-set="material-icons">date_range</md-icon></md-button>
						<%=@car.created_at.strftime("%d %b. %Y, %H:%M") %></div>

						<% if @car.notes != nil %>
						<div>
						<md-button class='md-icon-button'><md-icon md-font-set="material-icons">note</md-icon></md-button>
						<%=@car.notes%>
						</div>
						<% end %>
						</div>
</md-card>

<% @car.comments.each do |comment| %>

	<md-card layout="row" layout-padding>
		<div>
			<md-button class="md-fab"><md-icon md-font-set="material-icons">comment</md-icon></md-button>
		</div>
		<div flex= layout="column"  layout-align="space-between start">
			<div><%= comment.user.username.capitalize %> said:</div>
			<div class="md-title" layout-padding><%= comment.content %></div>
			<div><%= comment.created_at.strftime("%d %b. %Y, %H:%M") %></div>
		</div>
		<% if current_user.isadmin %>
		<div layout="column" layout-align="center center">
			<md-button class="md-button md-raised">DELETE</md-button>
		</div>
		<% end %>
	</md-card>
<% end %>
<% if did_login? %>
	<md-card layout="row" layout-padding>
		<div>
			<md-button class="md-fab"><md-icon md-font-set="material-icons">comment</md-icon></md-button>
		</div>
    <%= form_for :comment,html:{ flex: "", layout: "row", 'layout-align': "start start"}, url: car_comments_path(@car.id)  do |f| %>
    <%= f.text_area(:content, cols: 1,rows: 1, :style => 'display: none')%>
    <md-input-container class="md-block" flex>
        <label>Comment</label>
        <textarea ng-change="contentChanged()" ng-model="comment" md-maxlength="256" rows="5" md-select-on-focus></textarea>
    </md-input-container>
    <md-button class="md-raised" type="submit">comment</md-button>
    <%end%>
	</md-card>
<% end %>

</div>
<div flex="10" hide-xs hide-sm></div>
</div>