config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

	get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'

	get		'/info/' => 'info#index', as: :info

	resources :users do
	  resources :favorites
	end
	resources :cars do
		resources :comments

	end

  get  '/users/:id/cars' => 'users#cars', as: :user_cars
  get  '/users/:id/favs' =>'users#favs', as: :user_favs

	get '/admin/cars' => 'admin#cars', as: :admin_cars
	get '/admin/users' => 'admin#users', as: :admin_users
  post '/cars/s/search' => 'cars#search', as: :cars_search

  get '/api/users' =>'api#users'
  get '/api/cars'  =>'api#cars'
  get '/api/carsfavs' => 'api#carsfavs'
  post '/api/cars' => 'api#create'
  get '/api/favs'  =>'api#favs'
  get '/api/favdestroy' => 'api#favsdestroy'
  post '/api/favs' => 'api#createfavs'
  get '/api/comments' =>'api#comments'
  post '/api/comments' => 'api#createcomments'
	get '/api/login' => 'api#login'
  post '/api/signup' => 'api#signup'
  get '/api/sort' => 'api#sort'

end

app/views/layouts/_footer.html.erb
<md-toolbar>
	<span flex></span>
	<h2 class="md-toolbar-tools md-toolbar-tools-bottom">
		<span flex></span>
		Made with &#x2764 by Jolin and Shane
		<span flex></span>
	</h2>
</md-toolbar>

app/views/layouts/_header.html.erb
<md-toolbar class="md-tall header-toolbar">
	<div class="md-toolbar-tools">
		<span flex="10" hide-sm hide-xs></span>
		<%= link_to 'CARTOPIA', root_path %>
		<span flex></span>
		<%= link_to 'BUY', cars_path %>
		<%= link_to 'SELL', new_car_path %>
		<%= link_to 'INFO', info_path %>

<% if did_login? %>

<md-menu md-position-mode="target-right target" >
          <md-button class="md-icon-button" ng-click="$mdOpenMenu($event)">
			<md-icon md-font-set="material-icons">account_circle</md-icon>
			<md-tooltip md-direction="down"><%= current_user.username%></md-tooltip>
          </md-button>
          <md-menu-content width="1" >
            <md-menu-item>
              <md-button ng-href="<%=user_cars_path(current_user)%>">
                MY CARS
              </md-button>
            </md-menu-item>
            <md-menu-item>
              <md-button ng-href="<%=user_favs_path(current_user)%>">
								MY FAVS
              </md-button>
            </md-menu-item>

            <md-menu-item>
              <md-button ng-href="<%=logout_path%>" data-method="delete">
                  LOGOUT
              </md-button>
            </md-menu-item>
          </md-menu-content>
        </md-menu>

<% else %>

<md-menu md-position-mode="target-right target" >
          <md-button class="md-icon-button" ng-click="$mdOpenMenu($event)">
			<md-icon md-font-set="material-icons">account_circle</md-icon>
          </md-button>
          <md-menu-content width="1" >
            <md-menu-item>
              <md-button ng-href="<%= login_path%>">
                LOGIN
              </md-button>
            </md-menu-item>
            <md-menu-item>
              <md-button ng-href="<%= new_user_path %>">
                SIGNUP
              </md-button>
            </md-menu-item>
          </md-menu-content>
        </md-menu>
<% end %>


		<span flex="10" hide-sm hide-xs></span>
	</div>
</md-toolbar>

app/views/layouts/application.html.erb
<!DOCTYPE html> <html>
<head>
  <title>Cartopia</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag    'application', controller_name,  media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body ng-app="cartopia" ng-controller="AppCtrl">

	<%= render 'layouts/header' %>

  <%= yield %>

	<%= render 'layouts/footer' %>

</body>

</html>